### Create Doctor
POST http://localhost:8000/api/doctor/store
Content-Type: application/json

{
    "first_name": "Norah",
    "last_name": "Machatha",
    "middle_name": "Muthoni",
    "birth_date": "1/12/2000",
    "gender": "female",
    "email": "norah@email.com",
    "phone": "07000000001",
    "address": "Naiobi",
    "role_id": "1"
}

###



